#!/usr/bin/env python3
"""Independent cross-language check of vectors/webhook-signatures.json.

The corpus is generated by Node (scripts/generate-vectors.mjs). This verifier is
written in Python on purpose: if two independent implementations agree on every
case, the vectors are language-neutral and an SDK in any language can trust them.

Run: python3 scripts/verify_vectors.py
Exits non-zero on the first disagreement.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import sys
from pathlib import Path

VECTORS = Path(__file__).resolve().parent.parent / "vectors" / "webhook-signatures.json"
ALGOS = {"HMAC-SHA-512": hashlib.sha512, "HMAC-SHA-256": hashlib.sha256}


def verify(secret: str, body: str, signature: str, algo: str) -> bool:
    """Mirror of what every SDK must do: recompute over raw bytes, compare in
    constant time, and treat hex as case-insensitive."""
    if not signature:
        return False
    expected = hmac.new(secret.encode(), body.encode(), ALGOS[algo]).hexdigest()
    try:
        got = bytes.fromhex(signature)
    except ValueError:
        return False
    exp = bytes.fromhex(expected)
    return len(got) == len(exp) and hmac.compare_digest(got, exp)


def main() -> int:
    doc = json.loads(VECTORS.read_text())
    secret = doc["secret"]
    window = doc["replay_window_seconds"]
    failures: list[str] = []
    checked = 0

    for scheme_name, scheme in doc["schemes"].items():
        algo = scheme["algorithm"]

        for case in scheme["cases"]:
            checked += 1
            got = verify(secret, case["body"], case["signature"], algo)
            if got is not case["valid"]:
                failures.append(
                    f"{scheme_name}/{case['name']}: expected valid={case['valid']}, got {got}"
                )

        for case in scheme["replay_cases"]:
            checked += 1
            sig_ok = verify(secret, case["body"], case["signature"], algo)
            payload = json.loads(case["body"]) if case["body"].startswith("{") else {}
            ts = payload.get(scheme["timestamp_field"]) if scheme["timestamp_field"] else None
            fresh = ts is not None and abs(case["now"] - ts) <= window
            accepted = sig_ok and fresh
            if accepted is not case["accept"]:
                failures.append(
                    f"{scheme_name}/replay/{case['name']}: expected accept="
                    f"{case['accept']}, got {accepted} (sig_ok={sig_ok}, fresh={fresh})"
                )

    # Cross-scheme confusion: the bug that made 20 of 21 plugins fail.
    for case in doc["cross_scheme_confusion"]["cases"]:
        if "verify_as" not in case:
            continue
        checked += 1
        algo = doc["schemes"][case["verify_as"]]["algorithm"]
        got = verify(secret, case["body"], case["signature"], algo)
        if got is not case["valid"]:
            failures.append(f"cross_scheme/{case['name']}: expected {case['valid']}, got {got}")

    # Every scheme must declare a distinct header — the whole point.
    headers = {s["header"].lower() for s in doc["schemes"].values()}
    if len(headers) != len(doc["schemes"]):
        failures.append("two schemes share a signature header name")

    for f in failures:
        print(f"  FAIL {f}")
    print(f"{checked - len(failures)}/{checked} cases agree between Node and Python")
    if failures:
        return 1
    print("vectors are language-neutral")
    return 0


if __name__ == "__main__":
    sys.exit(main())
